import {
  Atom,
  BadgeCheck,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarRange,
  CheckCircle2,
  ClipboardList,
  Code,
  Compass,
  Crown,
  Database,
  Dna,
  FileText,
  FlaskConical,
  Flame,
  Footprints,
  GraduationCap,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  ListTodo,
  Mail,
  Megaphone,
  MessageSquare,
  Moon,
  NotebookPen,
  Palette,
  PenLine,
  Receipt,
  Regex,
  Repeat,
  ScanLine,
  ScanSearch,
  Shapes,
  Share2,
  ShieldCheck,
  Sparkles,
  SpellCheck,
  SquarePen,
  StickyNote,
  Sunrise,
  Timer,
  TrendingUp,
  Users,
  Wand2,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  Atom, BadgeCheck, BookOpen, Brain, BrainCircuit, Briefcase, Bug, Calculator,
  Calendar, CalendarClock, CalendarRange, CheckCircle2, ClipboardList, Code, Compass,
  Crown, Database, Dna, FileText, FlaskConical, Flame, Footprints, GraduationCap,
  Languages, Layers, LayoutDashboard, Library, ListChecks, ListTodo, Mail, Megaphone, MessageSquare, Moon, NotebookPen,
  Palette, PenLine, Receipt, Regex, Repeat, ScanLine, ScanSearch, Shapes, Share2,
  ShieldCheck, Sparkles, SpellCheck, SquarePen, StickyNote, Sunrise, Timer,
  TrendingUp, Users, Wand2, Zap,
}

export function ToolIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Sparkles
  return <Icon className={className} aria-hidden="true" />
}
